import { Row } from './row';

export const sampleData: Row[] = [
  {
    id: 1,
    name: 'Anna',
    email: 'anna@example.com',
    active: true,
    date: '2025-09-25',
  },
  {
    id: 2,
    name: 'Bence',
    email: 'bence@example.com',
    active: false,
    date: '2025-06-18',
  },
  {
    id: 3,
    name: 'Csilla',
    email: 'csilla@example.com',
    active: true,
    date: '2025-06-19',
  },
  {
    id: 4,
    name: 'Dániel',
    email: 'daniel@example.com',
    active: false,
    date: '2025-07-19',
  },
  {
    id: 5,
    name: 'Erika',
    email: 'erika@example.com',
    active: true,
    date: '2025-09-19',
  },
  {
    id: 6,
    name: 'Ferenc',
    email: 'ferenc@example.com',
    active: false,
    date: '2025-12-19',
  },
  {
    id: 7,
    name: 'Gábor',
    email: 'gabor@example.com',
    active: true,
    date: '2025-06-19',
  },
  {
    id: 8,
    name: 'Hanna',
    email: 'hanna@example.com',
    active: false,
    date: '2025-06-19',
  },
  {
    id: 9,
    name: 'István',
    email: 'istvan@example.com',
    active: true,
    date: '2025-06-19',
  },
  {
    id: 10,
    name: 'Judit',
    email: 'judit@example.com',
    active: false,
    date: '2025-06-19',
  },
  {
    id: 11,
    name: 'Anna',
    email: 'anna@example.com',
    active: false,
    date: '2025-06-19',
  },
  {
    id: 12,
    name: 'Bence',
    email: 'bence@example.com',
    active: true,
    date: '2025-06-19',
  },
  {
    id: 13,
    name: 'Csilla',
    email: 'csilla@example.com',
    active: false,
    date: '2025-06-19',
  },
  {
    id: 14,
    name: 'Dániel',
    email: 'daniel@example.com',
    active: true,
    date: '2025-06-19',
  },
  {
    id: 15,
    name: 'Erika',
    email: 'erika@example.com',
    active: false,
    date: '2025-06-19',
  },
  {
    id: 16,
    name: 'Ferenc',
    email: 'ferenc@example.com',
    active: true,
    date: '2025-06-19',
  },
  {
    id: 17,
    name: 'Gábor',
    email: 'gabor@example.com',
    active: false,
    date: '2025-06-19',
  },
  {
    id: 18,
    name: 'Hanna',
    email: 'hanna@example.com',
    active: true,
    date: '2025-06-19',
  },
  {
    id: 19,
    name: 'István',
    email: 'istvan@example.com',
    active: false,
    date: '2025-06-19',
  },
  {
    id: 20,
    name: 'Judit',
    email: 'judit@example.com',
    active: true,
    date: '2025-06-19',
  },
];
